### ISSUE TITLE
TestRussianG2P.test_phrase_to_phonemes_negative003 error

### ISSUE THREAD

**Issue by nsu-ai** [nsu-ai/russian_g2p#10]
Test log:

```
ERROR: test_phrase_to_phonemes_negative003 (__main__.TestRussianG2P)
Генерация исключения, если фраза содержит только неалфавитные символы, хоть и допустимые.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 426, in test_phrase_to_phonemes_negative003
    self.__g2p.phrase_to_phonemes(source_phrase)
  File "/media/dino/DATA/ASR/russian_g2p/russian_g2p/Grapheme2Phoneme.py", line 154, in phrase_to_phonemes
    last_letter = clear_word[-1]
IndexError: string index out of range
```

Apparently, the "word" is cleared that there is no longer a symbol (empty string), so error occurs

**Comment by nsu-ai** [comment]
Not a bug. Transcriptor does not receive non-preprocessed data.
