### ISSUE TITLE
Problem with accented texts in the `Transcription` class

### ISSUE THREAD

**Issue by bond005** [nsu-ai/russian_g2p#15]
If we use the `transcribe` method of the `Transcription` class, then we can see a strange bug:

1. When we pass a source string without any accention symbols, this method works correctly:

```
>>> Transcription().transcribe('диалог был')
[['D0', 'I', 'A', 'L', 'O0', 'G', 'B', 'Y0', 'L']]
```

2. But when we pass the source string with accentuation, this method raises exception:

```
>>> Transcription().transcribe('диало+г бы+л')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/my_projects/python/russian_g2p/russian_g2p/Transcription.py", line 8, in transcribe
    accented_text = Accentor().do_accents(words_and_tags)
  File "/home/user/my_projects/python/russian_g2p/russian_g2p/Accentor.py", line 283, in do_accents
    return self.__do_accents(prepared_phrase, morphotags_of_phrase)
  File "/home/user/my_projects/python/russian_g2p/russian_g2p/Accentor.py", line 525, in __do_accents
    for vt in self.__do_accents(words_list[1:], None if morphotags_list is None else morphotags_list[1:]):
  File "/home/user/my_projects/python/russian_g2p/russian_g2p/Accentor.py", line 505, in __do_accents
    if (len(accented_wordforms) != 1) or (len(accented_wordforms_many) != 1):
UnboundLocalError: local variable 'accented_wordforms_many' referenced before assignment
```

**Comment by bond005** [comment]
Fixed.
