### ISSUE TITLE
Problem rnnmorph inside Preprocessor

### ISSUE THREAD

**Issue by nsu-ai** [nsu-ai/russian_g2p#16]
When initialising Preprocessor or Transcription:
```
======================================================================
ERROR: test_tags (__main__.TestPrep)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 620, in setUp
    self.__prep = Preprocessor()
  File "/media/dino/DATA/ASR/russian_g2p/russian_g2p/Preprocessor.py", line 10, in __init__
    self.predictor = RNNMorphPredictor(language="ru")
  File "/home/dino/my_py3/lib/python3.5/site-packages/rnnmorph/predictor.py", line 88, in __init__
    self.model.load_eval(self.build_config, eval_model_config_path, eval_model_weights_path)
  File "/home/dino/my_py3/lib/python3.5/site-packages/rnnmorph/model.py", line 135, in load_eval
    self.eval_model = model_from_yaml(f.read(), custom_objects=custom_objects)
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/engine/saving.py", line 352, in model_from_yaml
    return deserialize(config, custom_objects=custom_objects)
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/engine/network.py", line 1046, in from_config
    process_node(layer, node_data)
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/engine/network.py", line 1003, in process_node
    layer(input_tensors[0], **kwargs)
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/layers/recurrent.py", line 500, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/engine/base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/layers/recurrent.py", line 2112, in call
    initial_state=initial_state)
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/layers/recurrent.py", line 609, in call
    input_length=timesteps)
  File "/home/dino/my_py3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2957, in rnn
    maximum_iterations=input_length)
TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'
```

Probably connected to renewing the rnnmorph and keras version.

**Comment by nsu-ai** [comment]
Seems to be connected with the OS. The issue occurs with Ubuntu 14.06. It is advised to install the rnnmorph of earlier version (0.2) and remove the language parameter in the code of russian_g2p.
