### ISSUE TITLE
ModuleNotFoundError: No module named 'russian_g2p.modes'

### ISSUE THREAD

**Issue by shkarupa-alex** [nsu-ai/russian_g2p#20]
It seems like __init__.py missed in russian_g2p/modes/

>>> from russian_g2p.Grapheme2Phoneme import Grapheme2Phoneme
>>> your_transcriptor = Grapheme2Phoneme()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/russian_g2p/Grapheme2Phoneme.py", line 11, in __init__
    RulesForGraphemes.__init__(self, users_mode)
  File "/usr/local/lib/python3.6/site-packages/russian_g2p/RulesForGraphemes.py", line 6, in __init__
    from russian_g2p.modes.Modern import ModernMode as UsersMode
ModuleNotFoundError: No module named 'russian_g2p.modes'

**Comment by nsu-ai** [comment]
Thank you for the feedback! The issue is fixed in "bugfixing" branch, awaiting merge.

**Comment by nsu-ai** [comment]
Fixed in [https://github.com/nsu-ai/russian_g2p/commit/ad0832b8eff3d933448e6de0727deba71ac8d10c](ad0832b)
