### ISSUE TITLE
TestAll.test_begin error

### ISSUE THREAD

**Issue by nsu-ai** [nsu-ai/russian_g2p#9]
test.py log for TestAll.test_begin

```
ERROR: test_begin (__main__.TestAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 701, in test_begin
    real_variants = self.__transcription.transcribe(source_phrase)
  File "/media/dino/DATA/ASR/russian_g2p/russian_g2p/Transcription.py", line 7, in transcribe
    words_and_tags = Preprocessor().preprocessing(text)
  File "/media/dino/DATA/ASR/russian_g2p/russian_g2p/Preprocessor.py", line 26, in preprocessing
    words_and_tags = self.gettags(text.split(' '))
  File "/media/dino/DATA/ASR/russian_g2p/russian_g2p/Preprocessor.py", line 12, in gettags
    analysis = self.predictor.predict_sentence_tags(text)
  File "/home/dino/my_py3/lib/python3.5/site-packages/rnnmorph/predictor.py", line 72, in predict_sentence_tags
    tags = self.model.predict([words])[0]
  File "/home/dino/my_py3/lib/python3.5/site-packages/rnnmorph/model.py", line 262, in predict
    for sentence, probs in zip(sentences, self.predict_proba(sentences)):
  File "/home/dino/my_py3/lib/python3.5/site-packages/rnnmorph/model.py", line 248, in predict_proba
    self.grammeme_vectorizer_input, self.max_word_len)
  File "/home/dino/my_py3/lib/python3.5/site-packages/rnnmorph/batch_generator.py", line 90, in get_sample
    char_indices[-min(len(word), max_word_len):] = word_char_indices
ValueError: cannot copy sequence with size 0 to array axis with dimension 30
```

Assumption: rnnmorph cannot predict tag of an empty string

**Comment by nsu-ai** [comment]
Fixed in Preprocessor.
